version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    restart: 'no'

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    restart: 'no'
    depends_on:
      server:
        condition: service_started

